### ISSUE TITLE
DocProduct dataset links seem to be offline

### ISSUE THREAD

**Issue by bodak** [Santosh-Gupta/Datasets#1]
I think the problem is that they were moved to trash on your Google Drive @JayYip

**Comment by JayYip** [comment]
@Santosh-Gupta Could you update the link? My Google drive is running out of space.

**Comment by Santosh-Gupta** [comment]
@JayYip could you restore the files from Trash? Then I'll be able to make a copy of them. 

If it's in trash, it's already taking up memory so taking it out of the trash won't affect your free memory. 

Edit:

Unless we already have a link to some unified and complete data.

**Comment by JayYip** [comment]
Restored. Please check. Sorry for the late reply.

**Comment by Santosh-Gupta** [comment]
@JayYip could you link the folder? This looks like a direct file download, so I don't see an option to copy to google drive

**Comment by JayYip** [comment]
I don't know what you need exactly so here's what I got. Please let me know after you're done. 

https://drive.google.com/open?id=1PymmjbrgfOIs-HJ7oBmjZKH8j4rYsGZj
https://drive.google.com/open?id=1A_b6-EN8vbNdvMI9gNIxR0XnHEGGLH-6
https://drive.google.com/open?id=1zMC1Nm8wChJoVY4PDMnjzl7LSsQmhy_h
https://drive.google.com/open?id=1QeH-t0Wiunfb5kUh6yrwn0qTOuE0Y4bZ
https://drive.google.com/open?id=1wRc1jtl5Q0objpfualNFwpg4H575tmks
https://drive.google.com/open?id=1kYD57uStDd4kXyb3JOYCTQd92Al6Il4K
https://drive.google.com/open?id=1Q6Em4Y5PMSOMl_E-HwEMeE9v76XzhBQv

**Comment by Santosh-Gupta** [comment]
Yeah, that's pretty much it!

I'm going to be looking for space in my gdrive to fit these in. Stay Tuned. 

I'm trying to organize them. Do you remember what MQA means? 

Also, I was wondering if we can perhaps delete the FFNN-only stuff? Since it turned out fine-tuning the whole thing worked out, I don't think people would want to use it. They would need to load either ours or if not ours, BioBert. 

Also, any use in keeping the tfrecords files if you're not training DocProduct further? The users can just create new ones on their systems. 

I'm going to also post this in the slack.

**Comment by JayYip** [comment]
I this MQA means medical QA. Yes, I think we can delete FFNN-only. But I think it's not big. Your choice.
